import BYC from './BYC LOGO JPG FILE 1.png';
import Frame26 from './Frame 26.png'
import Group84 from './Group 84.png'
import Group41 from './Frame 41.png'
import Group42 from './Frame 42.png'
import Group34 from './Frame 34.png'
import Frame167 from './Frame 167.png'
import Frame168 from './Frame 168.png'
import Frame166 from './Frame 166.png'
import Arrowleft from './Arrow_Left.png'
import Pant1 from './pant1.png'
import Pant2 from './pant2.png'
import Pant3 from './pant3.png'
import Arrowright from './Arrow_right.png'
import Frame169 from './Frame 169.png'
import Frame169a from './Frame 169a.png'
import Frame169b from './Frame 169b.png'
import Arrow from './Arrow.png'
import Authorview from './Author + Views.png'
import Payment from './Payments.png'
import HR from './HR.png'
import Social from './Social Media.png'
import Email from './Mail.png'
import Phone from './Phone.png'
import Numberarrow from './number arrow.png'
import Frame171 from './Frame 171.png'
import Frame178 from './Frame 178.png'
import Award from './awards.png'
import Angleright from './angle-right.png'
import Singlet from './singlet.png'
import Stars from './Stars.png'
import Map from './map.png'
import Fone from './fone.png'
import Mail from './email.png'
import Address from './address.png'
import Arthur from './arthur.png'
import Frame170 from './Frame 170.png'
import Frame170a from './Frame 170a.png'
import Boxer from './Boxer.png'
import Boxer1 from './Boxer1.png'
import Boxer2 from './Boxer2.png'
import Boxer3 from './Boxer3.png'
import Blue from './blue boxer.png'
import Oneboxer from './one boxer.png'
import Threeinone from './three in one.png'
import Smallblue from './blue small.png'
import Bigblue from './blue big.png'
import Smallbox from './small box.png'
import Pay from './Pay.png'
import Sort from './sortby.png'
import Filter from './filter.png'






export {BYC, Frame26, Group84, Sort, Filter, Group41, Pay, Smallblue, Bigblue, Smallbox, Group42, Group34, Blue, Oneboxer, Threeinone,  Boxer, Boxer1, Boxer2, Boxer3, Frame167, Frame170, Frame168, Frame170a, Frame166, Arrowleft, Pant1, Pant2, Pant3, Arrowright, Frame169, Frame169a, Frame169b, Arrow, Authorview, Payment, HR, Social, Email, Phone, Numberarrow, Frame171, Frame178, Award, Angleright, Singlet, Stars, Mail, Map, Fone, Address, Arthur}